name: Deploy PR previews

on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency: preview-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:
  build-preview:
    name: Build and Archive
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ">=1.21.5"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: "0.144.2"
          extended: true

      - uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build S-CORE Hugo Website
        shell: bash
        env:
          SITE_URL: https://eclipse-score.github.io/eclipse-score-website-preview/pr-preview/pr-${{ github.event.number }}
        run: |
          mkdir -p themes/hugo-solstice-theme
          hugo --minify -b "${SITE_URL}"
          
      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: "site"
          path: ./public

  deploy-preview:
    needs: build-preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    environment:
      name: pull-request-preview
      url: ${{ steps.deployment.outputs.deployment-url }}
    steps:
      # checkout required for pr-preview-action to succeed,
      # while the content will not be used
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download the preview page
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: "site"
          path: ./public
      - uses: rossjrw/pr-preview-action@f31d5aa7b364955ea86228b9dcd346dc3f29c408 # v1.4.7
        id: deployment
        with:
          source-dir: ./public
          preview-branch: gh-pages-preview
          umbrella-dir: pr-preview
          deploy-repository: eclipse-score/eclipse-score-website-preview
          token: ${{ secrets.GH_PUBLISH_TOKEN }}
          action: auto

  # remove the preview page when the PR got closed
  remove-preview:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # checkout required for pr-preview-action to succeed,
      # while the content will not be used
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: rossjrw/pr-preview-action@f31d5aa7b364955ea86228b9dcd346dc3f29c408 # v1.4.7
        id: deployment
        with:
          preview-branch: gh-pages-preview
          umbrella-dir: pr-preview
          deploy-repository: eclipse-score/eclipse-score-website-preview
          token: ${{ secrets.GH_PUBLISH_TOKEN }}
          action: auto